default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.241"
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: debug-statements
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/horta/sanitize-pyproject-version
    rev: v0.0.4
    hooks:
      - id: check-version-equality
